#!/usr/bin/env zsh

# If there are any failures, stop running subsequent tests
set -e

if [ $1 = "all" ]; then
    for chapter in $(find . -name 'ch*' -type d); do
        echo $chapter
        racket $chapter/tests.rkt
    done
else
    racket ch$1/tests.rkt
fi
